name: cal_importance-run_cal_importance_ranking

category_root_path: ./tmp/trash
# category_root_path: ./tmp/importance_probe/run_sd_family/anime/sd-turbo/step-2_seed-42

eps: 1e-6

importance_score:
  save_importance_score: True
  save_prefix_importance_score: True

importance_ranking:
  save_importance_ranking: True
  save_prefix_importance_ranking: True

skipping_stategy:
  save_strategy_skip_1: True
  save_strategy_skip_2: True
