load_pipeline: True

# SDXL
pipeline_type: StableDiffusionXLPipeline
pipeline_path: /root/autodl-tmp/stabilityai/stable-diffusion-xl-base-1.0/
torch_dtype: float16
variant: fp16

scheduler: "DDIMScheduler"
# scheduler: "DDPMScheduler"
# scheduler: "PNDMScheduler"
# scheduler: "EulerDiscreteScheduler"
