#!/bin/bash

# defaults
DEFAULT_GPU_ID=0

# GPU ID
gpu_id=${1:-$DEFAULT_GPU_ID}
export CUDA_VISIBLE_DEVICES=${gpu_id}

# baselines (training set)
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-0"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-1"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-4"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-0,6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-1,5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_static-2,4"'

# baselines (test set)
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-0"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-1"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-4"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-0,6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-1,5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_static-2,4"'

# ours (training set)
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-1_0"'
# python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-1_1"'
# python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-1_2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-1_3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_0"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_1"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_4"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_7"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-42/some_cut_up_fruit/png/default_skip-2_8"'

# ours (test set)
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-1_0"'
# python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-1_1"'
# python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-1_2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-1_3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-1_4"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_0"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_1"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_2"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_3"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_4"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_5"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_6"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_7"'
python main.py task=cal_metric/run_cal_fid_lpips task.img.ref_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_default"' task.img.gen_img_root_path='"./tmp/sample/sd_family/sd-turbo/step-2_seed-21/some_cut_up_fruit/png/default_skip-2_8"'
